// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package main

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ComponentType.
const (
	Noodle  ComponentType = "noodle"
	Oil     ComponentType = "oil"
	Plating ComponentType = "plating"
	Soup    ComponentType = "soup"
	Tare    ComponentType = "tare"
	Topping ComponentType = "topping"
)

// Component defines model for Component.
type Component struct {
	Id   string        `json:"id"`
	Type ComponentType `json:"type"`
}

// ComponentType defines model for Component.Type.
type ComponentType string

// CustomerCategory defines model for CustomerCategory.
type CustomerCategory struct {
	Id         string             `json:"id"`
	Name       string             `json:"name"`
	Preference map[string]int     `json:"preference"`
	Weight     map[string]float32 `json:"weight"`
}

// Evaluation defines model for Evaluation.
type Evaluation struct {
	Metrics  map[string]uint16 `json:"metrics"`
	RecipeId string            `json:"recipeId"`
}

// MatchingRequest defines model for MatchingRequest.
type MatchingRequest struct {
	CustomerId string `json:"customerId"`
	RecipeId   string `json:"recipeId"`
}

// MatchingResult defines model for MatchingResult.
type MatchingResult struct {
	Comment    *string  `json:"comment,omitempty"`
	CustomerId *string  `json:"customerId,omitempty"`
	RecipeId   *string  `json:"recipeId,omitempty"`
	Score      *float32 `json:"score,omitempty"`
}

// RecipeInput defines model for RecipeInput.
type RecipeInput struct {
	Components []Component `json:"components"`
	Name       string      `json:"name"`
}

// PostMatchJSONRequestBody defines body for PostMatch for application/json ContentType.
type PostMatchJSONRequestBody = MatchingRequest

// PostRecipesJSONRequestBody defines body for PostRecipes for application/json ContentType.
type PostRecipesJSONRequestBody = RecipeInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 顧客カテゴリの一覧を取得する
	// (GET /customers)
	GetCustomers(c *gin.Context)
	// レシピと顧客カテゴリをマッチングして評価スコアを返す
	// (POST /match)
	PostMatch(c *gin.Context)
	// レシピを作成する
	// (POST /recipes)
	PostRecipes(c *gin.Context)
	// 指定したレシピを評価する（10軸）
	// (GET /recipes/{id}/evaluate)
	GetRecipesIdEvaluate(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCustomers operation middleware
func (siw *ServerInterfaceWrapper) GetCustomers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCustomers(c)
}

// PostMatch operation middleware
func (siw *ServerInterfaceWrapper) PostMatch(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostMatch(c)
}

// PostRecipes operation middleware
func (siw *ServerInterfaceWrapper) PostRecipes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRecipes(c)
}

// GetRecipesIdEvaluate operation middleware
func (siw *ServerInterfaceWrapper) GetRecipesIdEvaluate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRecipesIdEvaluate(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/customers", wrapper.GetCustomers)
	router.POST(options.BaseURL+"/match", wrapper.PostMatch)
	router.POST(options.BaseURL+"/recipes", wrapper.PostRecipes)
	router.GET(options.BaseURL+"/recipes/:id/evaluate", wrapper.GetRecipesIdEvaluate)
}
