// Code generated by "stringer -type=MetricKey"; DO NOT EDIT.

package logic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Umami-0]
	_ = x[Aroma-1]
	_ = x[Salt-2]
	_ = x[Fat-3]
	_ = x[Sweet-4]
	_ = x[Spicy-5]
	_ = x[Creative-6]
	_ = x[Appearance-7]
	_ = x[Volume-8]
	_ = x[Harmony-9]
}

const _MetricKey_name = "UmamiAromaSaltFatSweetSpicyCreativeAppearanceVolumeHarmony"

var _MetricKey_index = [...]uint8{0, 5, 10, 14, 17, 22, 27, 35, 45, 51, 58}

func (i MetricKey) String() string {
	if i < 0 || i >= MetricKey(len(_MetricKey_index)-1) {
		return "MetricKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MetricKey_name[_MetricKey_index[i]:_MetricKey_index[i+1]]
}
